/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "border-focus": "#0284C7",
        "status-cancelled-bg": "#FFE4E6",
        "on-primary": "#ffffff",
        "border-subtle": "#E2E8F0",
        "status-completed-text": "#047857",
        "tertiary-fixed": "#c9e6ff",
        "primary-fixed": "#cce5ff",
        "status-scheduled-text": "#0369A1",
        "canvas-bg": "#E9EEF5",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#89ceff",
        "on-tertiary-fixed": "#001e2f",
        "inverse-surface": "#213145",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed-variant": "#3f465c",
        "background": "#f8f9ff",
        "surface-subtle": "#F1F5F9",
        "secondary": "#565e74",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "status-pending-text": "#B45309",
        "on-tertiary-container": "#fcfcff",
        "status-completed-bg": "#D1FAE5",
        "outline-variant": "#bfc7d2",
        "on-tertiary-fixed-variant": "#004c6e",
        "surface-variant": "#d3e4fe",
        "on-surface-variant": "#3f4850",
        "surface-container-low": "#eff4ff",
        "secondary-container": "#dae2fd",
        "brand-navy-deep": "#0F172A",
        "surface-container-high": "#dce9ff",
        "on-secondary-container": "#5c647a",
        "secondary-fixed-dim": "#bec6e0",
        "tertiary-container": "#007cb1",
        "inverse-primary": "#93ccff",
        "secondary-fixed": "#dae2fd",
        "on-secondary-fixed": "#131b2e",
        "primary": "#006194",
        "surface-tint": "#006398",
        "brand-teal-light": "#38BDF8",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "on-primary-fixed-variant": "#004b73",
        "surface-container-highest": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        "surface-container": "#e5eeff",
        "on-error-container": "#93000a",
        "outline": "#707881",
        "primary-fixed-dim": "#93ccff",
        "status-scheduled-bg": "#E0F2FE",
        "tertiary": "#00628d",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#fdfcff",
        "status-pending-bg": "#FEF3C7",
        "on-error": "#ffffff",
        "primary-container": "#007bb9",
        "on-primary-fixed": "#001d31",
        "status-cancelled-text": "#BE123C",
        "surface-card": "#FFFFFF",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "sidebar-collapsed-width": "72px",
        "space-xs": "0.5rem",
        "gutter-desktop": "1.5rem",
        "space-sm": "0.75rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xs": "0.25rem",
        "content-max-width": "1600px",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "sidebar-width": "260px",
        "topbar-height": "68px",
        "space-2xl": "2.5rem",
        "space-3xl": "3rem",
      },
      fontFamily: {
        sans: ["'Roboto'", "sans-serif"],
        "label-sm": ["'Roboto'", "sans-serif"],
        "display-lg-mobile": ["'Roboto'", "sans-serif"],
        "headline-md": ["'Roboto'", "sans-serif"],
        "headline-sm": ["'Roboto'", "sans-serif"],
        "display-lg": ["'Roboto'", "sans-serif"],
        "body-sm": ["'Roboto'", "sans-serif"],
        "label-md": ["'Roboto'", "sans-serif"],
        "body-md": ["'Roboto'", "sans-serif"],
        "body-lg": ["'Roboto'", "sans-serif"],
        "mono-data": ["'Roboto'", "sans-serif"],
        "label-lg": ["'Roboto'", "sans-serif"],
        "headline-lg": ["'Roboto'", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "display-lg": ["34px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-lg": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        "mono-data": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-lg": ["15px", { lineHeight: "22px", fontWeight: "600" }],
        "headline-lg": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
