from datetime import date
from .common import GenderEnum
from typing import Annotated, List, Optional
from pydantic import BaseModel, EmailStr, Field


# Base field shared across doctor models
class DoctorBase(BaseModel):
    first_name: str = Field(..., min_length=1, max_length=60)
    middle_name: Optional[str] = Field(None, max_length=60)
    last_name: str = Field(..., min_length=1, max_length=60)
    
    id_number: str = Field(
        ...,
        pattern=r"^([0-9]{9}[VvXx]|[0-9]{12})$",
        description="Valid Sri Lankan NIC (9 digits + letter or 12 digits)",
    )

    address: str = Field(..., min_length=3, max_length=255)
    marital_status: Optional[str] = Field(None, max_length=20)
    birthdate: date
    gender: GenderEnum

    phone_numbers: List[Annotated[str, Field(pattern=r"^[0-9]{10}$")]] = Field(
        ...,
        min_items=1,
        description="List of 10 digit contact numbers",
    )

    email: Optional[EmailStr] = None

    # staff specific
    branch_id: int = Field(..., description="Branch ID where doctor works")

# Request body when creating a doctor: POST /doctors
class DoctorCreate(DoctorBase):
    license_number: str = Field(..., min_length=1, max_length=50)
    specialty_ids: List[int] = Field(
        ...,
        min_items=1,
        description="Doctor must have at least one specialty assigned",
    )

# Request body for updating doctor profile: PUT /doctors/{id}
class DoctorUpdate(BaseModel):
    # only doctor specific parts
    license_number: str = Field(..., min_length=1, max_length=50)

# Request body for updating doctor specialties: PUT /doctors/{id}/specialties
class DoctorSpecialtiesUpdate(BaseModel):
    add: List[int] = Field(default_factory=list)
    remove: List[int] = Field(default_factory=list)


# Response model: GET /doctors/{id}
class DoctorResponse(BaseModel):
    doctor_id: int  # user_id
    full_name: str
    id_number: str
    phone_numbers: List[str] = []
    email: Optional[str] = None
    branch_id: int
    branch_name: Optional[str] = None
    license_number: str
    is_active: bool
    specialties: List[str] = []

# Generate a temporary password server-side
class DoctorCreateResponse(DoctorResponse):
    temp_password: str = Field(..., description="One-time temporary password generated by server")
